I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/start/start_game.rpy", line 88, in script
    sam "Hey  %(playerName)"
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/start/start_game.rpy", line 88, in script
    sam "Hey  %(playerName)"
  File "C:\Users\Ceejay\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Ceejay\Desktop\renpy-7.3.5-sdk\renpy\exports.py", line 1334, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Prime Mates 1.0
Tue Dec 01 19:14:47 2020
